function []=lfosr_edit(action)

if nargin < 1 %on start without input variables run initialize code
   action = 'initialize'; 
end 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%% END PROGRAM INPUT CONTROL %%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%% INITIALIZE PROGRAM INTERFACE %%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if strcmp(action,'initialize')
   
   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
   figLeft      = 132;
   figBottom    = 48;
   figWidth     = 760;
   figHt        = 520;
   
   center       = 0.5;
   spacing      = 0.01;
   spacing2     = 0.01;
   marginleft   = 0.02;
   sampletxtbot = 0.15;
   sampleWidth  = 0.45;
   
   txtWidth     = 0.12;
   txtHt        = 0.055;
   
   buttonBottom = 0.07;
   buttonWidth  = 0.17;
   buttonHt     = 0.06;
   smbutWidth   = 0.25;
   smbutHt      = 0.05;
   
   editWidth    = 0.15;
   editHt       = 0.10;
   smeditWidth  = 0.10;
   
   guibackcolor = [0.8 0.8 0.8];
   guibuttonbackcolor = [0.7 0.7 0.7];
   guitextcolor = [0 0 0];
   
   guiFontSize  = 12;
   
   fontbot      = sampletxtbot+4*(2*txtHt+spacing)+2*(smbutHt+spacing);
   
   %%%%%%%%%%%%%%%%% PROGRAM INPUT CONTROL %%%%%%%%%%%%%%%%%%%%%%%%%%%%
   %[path,name,ext] = fileparts(which(mfilename));
   
   %path and name of file plus Text Extension
   if isunix == 1
      fid = fopen('lfosr_unixfont.txt','r');
      
   % This is the font set up for all other systems
   else
      fid = fopen('lfosr_pcfont.txt','r');
      
   end
   
   if fid == -1 %check for error on open
      error('Unable to open file.')
   end
   
   FontName    = fgetl(fid);
   FontUnits   = fgetl(fid);
   FontSize    = str2double(fgetl(fid));
   FontWeight  = fgetl(fid);
   FontAngle   = fgetl(fid);
   StartFigTextColor = str2num(fgetl(fid));
   StartFigBackColor = str2num(fgetl(fid));
   OuputFigTextColor = str2num(fgetl(fid));
   OuputFigBackColor = str2num(fgetl(fid));
   ButtonTextColor   = str2num(fgetl(fid));
   ButtonBackcolor   = str2num(fgetl(fid));
   EditTextColor     = str2num(fgetl(fid));
   EditBackColor     = str2num(fgetl(fid));
   FrameTextColor    = str2num(fgetl(fid));
   FrameBackColor    = str2num(fgetl(fid));
   StartFigWidth     = str2double(fgetl(fid));
   StartFigHt        = str2double(fgetl(fid));
   OutputFigWidth    = str2double(fgetl(fid));
   OutputFigHt       = str2double(fgetl(fid));
   fclose(fid);
   
   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
   
   FigHandle = figure('Name','LFOSR GUI Editor',...
      'NumberTitle','off',...
      'Menubar','none',...
      'Position',[figLeft figBottom figWidth figHt],...
      'Color',guibackcolor, ...
      'Tag','lfosr_edit');
   
   %%%%%%%%%%%%%%%%%%%%%%%%%%% Headings %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
   %%%%%%%%% Title %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
   uicontrol('Parent',FigHandle, ...
      'Units','normalized', ...
      'HorizontalAlignment','center', ...
      'BackgroundColor',guibackcolor, ...
      'ForegroundColor',guitextcolor,...
      'FontSize',guiFontSize, ...
      'Position',[0 .93 1 txtHt], ...
      'String','Layered Film Optical Simulation Routine GUI Editor', ...
      'Style','text');
   %%%%%%%%%%%% Headings %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%   
   uicontrol('Parent',FigHandle, ...
      'Units','normalized', ...
      'HorizontalAlignment','left', ...
      'BackgroundColor',guibackcolor, ...
      'ForegroundColor',guitextcolor,...
      'FontSize',guiFontSize, ...
      'Position',[marginleft fontbot+editHt+spacing 2.5*txtWidth txtHt], ...
      'String','Font Name', ...
      'Style','text');
   FontName_H = uicontrol('Parent',FigHandle, ...
      'Units','normalized', ...
      'HorizontalAlignment','left', ...
      'BackgroundColor',guibackcolor, ...
      'ForegroundColor',guitextcolor,...
      'FontName',FontName,...
      'FontUnits',FontUnits,...
      'FontSize',FontSize, ...
      'FontWeight',FontWeight,...
      'FontAngle',FontAngle,...
      'Position',[marginleft fontbot 2.5*editWidth editHt], ...
      'String',FontName, ...
      'Style','text', ...
      'Tag','FontName_Menu');

   uicontrol('Parent',FigHandle, ...
      'Units','normalized', ...
      'HorizontalAlignment','left', ...
      'BackgroundColor',guibackcolor, ...
      'ForegroundColor',guitextcolor,...
      'FontSize',guiFontSize, ...
      'Position',[marginleft+3*(txtWidth+spacing2) fontbot+editHt+spacing txtWidth txtHt], ...
      'String','Units', ...
      'Style','text');
   FontUnits_H = uicontrol('Parent',FigHandle, ...
      'Units','normalized', ...
      'HorizontalAlignment','left', ...
      'BackgroundColor',guibackcolor, ...
      'ForegroundColor',guitextcolor,...
      'FontName',FontName,...
      'FontUnits',FontUnits,...
      'FontSize',FontSize, ...
      'FontWeight',FontWeight,...
      'FontAngle',FontAngle,...
      'Position',[marginleft+3*(txtWidth+spacing2) fontbot editWidth editHt], ...
      'String',FontUnits, ...
      'Style','text', ...
      'Tag','FontUnits_Menu');

   uicontrol('Parent',FigHandle, ...
      'Units','normalized', ...
      'HorizontalAlignment','left', ...
      'BackgroundColor',guibackcolor, ...
      'ForegroundColor',guitextcolor,...
      'FontSize',guiFontSize, ...
      'Position',[marginleft+4*(txtWidth+2*spacing2) fontbot+editHt+spacing txtWidth txtHt], ...
      'String','Size', ...
      'Style','text');
   FontSize_H = uicontrol('Parent',FigHandle, ...
      'Units','normalized', ...
      'HorizontalAlignment','left', ...
      'BackgroundColor',guibackcolor, ...
      'ForegroundColor',guitextcolor,...
      'FontName',FontName,...
      'FontUnits',FontUnits,...
      'FontSize',FontSize, ...
      'FontWeight',FontWeight,...
      'FontAngle',FontAngle,...
      'Position',[marginleft+4*(txtWidth+2*spacing2) fontbot editWidth editHt], ...
      'String',FontSize, ...
      'Style','text', ...
      'Tag','FontSize_Menu');

   uicontrol('Parent',FigHandle, ...
      'Units','normalized', ...
      'HorizontalAlignment','left', ...
      'BackgroundColor',guibackcolor, ...
      'ForegroundColor',guitextcolor,...
      'FontSize',guiFontSize, ...
      'Position',[marginleft+5*(txtWidth+spacing2) fontbot+editHt+spacing txtWidth txtHt], ...
      'String','Weight', ...
      'Style','text');
   FontWeight_H = uicontrol('Parent',FigHandle, ...
      'Units','normalized', ...
      'HorizontalAlignment','left', ...
      'BackgroundColor',guibackcolor, ...
      'ForegroundColor',guitextcolor,...
      'FontName',FontName,...
      'FontUnits',FontUnits,...
      'FontSize',FontSize, ...
      'FontWeight',FontWeight,...
      'FontAngle',FontAngle,...
      'Position',[marginleft+5*(txtWidth+spacing2) fontbot editWidth editHt], ...
      'String',FontWeight, ...
      'Style','text', ...
      'Tag','FontWeight_Menu');
   
   uicontrol('Parent',FigHandle, ...
      'Units','normalized', ...
      'HorizontalAlignment','left', ...
      'BackgroundColor',guibackcolor, ...
      'ForegroundColor',guitextcolor,...
      'FontSize',guiFontSize, ...
      'Position',[marginleft+6*(txtWidth+spacing2) fontbot+editHt+spacing txtWidth txtHt], ...
      'String','Angle', ...
      'Style','text');
   FontAngle_H = uicontrol('Parent',FigHandle, ...
      'Units','normalized', ...
      'HorizontalAlignment','left', ...
      'BackgroundColor',guibackcolor, ...
      'ForegroundColor',guitextcolor,...
      'FontName',FontName,...
      'FontUnits',FontUnits,...
      'FontSize',FontSize, ...
      'FontWeight',FontWeight,...
      'FontAngle',FontAngle,...
      'Position',[marginleft+6*(txtWidth+spacing2) fontbot editWidth editHt], ...
      'String',FontAngle, ...
      'Style','text', ...
      'Tag','FontAngle_Menu');
   
   %%%%%%%%%%%
   StartFigText_H = uicontrol('Parent',FigHandle, ...
      'Units','normalized', ...
      'HorizontalAlignment','left', ...
      'BackgroundColor',StartFigBackColor, ...
      'ForegroundColor',StartFigTextColor,...
      'FontName',FontName,...
      'FontUnits',FontUnits,...
      'FontSize',FontSize, ...
      'FontWeight',FontWeight,...
      'FontAngle',FontAngle,...
      'Position',[marginleft sampletxtbot+4*(2*txtHt+spacing) sampleWidth 2*txtHt], ...
      'String','This Is The Start Figure Sample Text', ...
      'Style','text');
   
   uicontrol('Parent',FigHandle, ...
      'Units','normalized', ...
      'BackgroundColor',guibuttonbackcolor, ...
      'ForegroundColor',guitextcolor,...
      'FontSize',guiFontSize, ...
      'Position',[marginleft+sampleWidth+spacing sampletxtbot+4*(2*txtHt+spacing) ...
         smbutWidth smbutHt], ...
      'UserData',StartFigText_H,...
      'String','Change Background Color',...
      'Callback','lfosr_edit(''changebackcolor'')');

   uicontrol('Parent',FigHandle, ...
      'Units','normalized', ...
      'BackgroundColor',guibuttonbackcolor, ...
      'ForegroundColor',guitextcolor,...
      'FontSize',guiFontSize, ...
      'Position',[marginleft+sampleWidth+spacing ...
         sampletxtbot+smbutHt+spacing+4*(2*txtHt+spacing) smbutWidth smbutHt], ...
      'String','Change Text Color', ...
      'UserData',StartFigText_H,...
      'Callback','lfosr_edit(''changetextcolor'')');
   
   
   OutputFigText_H = uicontrol('Parent',FigHandle, ...
      'Units','normalized', ...
      'HorizontalAlignment','left', ...
      'BackgroundColor',OuputFigBackColor, ...
      'ForegroundColor',OuputFigTextColor,...
      'FontName',FontName,...
      'FontUnits',FontUnits,...
      'FontSize',FontSize, ...
      'FontWeight',FontWeight,...
      'FontAngle',FontAngle,...
      'Position',[marginleft sampletxtbot+3*(2*txtHt+spacing) sampleWidth 2*txtHt], ...
      'String','This Is The Ouput Figure Sample Text', ...
      'Style','text');
   
   uicontrol('Parent',FigHandle, ...
      'Units','normalized', ...
      'BackgroundColor',guibuttonbackcolor, ...
      'ForegroundColor',guitextcolor,...
      'FontSize',guiFontSize, ...
      'Position',[marginleft+sampleWidth+spacing sampletxtbot+3*(2*txtHt+spacing) ...
         smbutWidth smbutHt], ...
      'UserData',OutputFigText_H,...
      'String','Change Background Color',...
      'Callback','lfosr_edit(''changebackcolor'')');

   uicontrol('Parent',FigHandle, ...
      'Units','normalized', ...
      'BackgroundColor',guibuttonbackcolor, ...
      'ForegroundColor',guitextcolor,...
      'FontSize',guiFontSize, ...
      'Position',[marginleft+sampleWidth+spacing ...
         sampletxtbot+3*(2*txtHt+spacing)+smbutHt+spacing smbutWidth smbutHt], ...
      'String','Change Text Color', ...
      'UserData',OutputFigText_H,...
      'Callback','lfosr_edit(''changetextcolor'')');
   
   
   ButtonText_H = uicontrol('Parent',FigHandle, ...
      'Units','normalized', ...
      'HorizontalAlignment','left', ...
      'BackgroundColor',ButtonBackcolor, ...
      'ForegroundColor',ButtonTextColor,...
      'FontName',FontName,...
      'FontUnits',FontUnits,...
      'FontSize',FontSize, ...
      'FontWeight',FontWeight,...
      'FontAngle',FontAngle,...
      'Position',[marginleft sampletxtbot+2*(2*txtHt+spacing) sampleWidth 2*txtHt], ...
      'String','This Is The Button Sample Text', ...
      'Style','text');
   
   uicontrol('Parent',FigHandle, ...
      'Units','normalized', ...
      'BackgroundColor',guibuttonbackcolor, ...
      'ForegroundColor',guitextcolor,...
      'FontSize',guiFontSize, ...
      'Position',[marginleft+sampleWidth+spacing sampletxtbot+2*(2*txtHt+spacing) ...
         smbutWidth smbutHt], ...
      'UserData',ButtonText_H,...
      'String','Change Background Color',...
      'Callback','lfosr_edit(''changebackcolor'')');

   uicontrol('Parent',FigHandle, ...
      'Units','normalized', ...
      'BackgroundColor',guibuttonbackcolor, ...
      'ForegroundColor',guitextcolor,...
      'FontSize',guiFontSize, ...
      'Position',[marginleft+sampleWidth+spacing ...
         sampletxtbot+2*(2*txtHt+spacing)+smbutHt+spacing smbutWidth smbutHt], ...
      'String','Change Text Color', ...
      'UserData',ButtonText_H,...
      'Callback','lfosr_edit(''changetextcolor'')');
   
   EditText_H = uicontrol('Parent',FigHandle, ...
      'Units','normalized', ...
      'HorizontalAlignment','left', ...
      'BackgroundColor',EditBackColor, ...
      'ForegroundColor',EditTextColor,...
      'FontName',FontName,...
      'FontUnits',FontUnits,...
      'FontSize',FontSize, ...
      'FontWeight',FontWeight,...
      'FontAngle',FontAngle,...
      'Position',[marginleft sampletxtbot+1*(2*txtHt+spacing) sampleWidth 2*txtHt], ...
      'String','This Is The Edit Sample Text', ...
      'Style','text');
   
   uicontrol('Parent',FigHandle, ...
      'Units','normalized', ...
      'BackgroundColor',guibuttonbackcolor, ...
      'ForegroundColor',guitextcolor,...
      'FontSize',guiFontSize, ...
      'Position',[marginleft+sampleWidth+spacing sampletxtbot+1*(2*txtHt+spacing) ...
         smbutWidth smbutHt], ...
      'UserData',EditText_H,...
      'String','Change Background Color',...
      'Callback','lfosr_edit(''changebackcolor'')');

   uicontrol('Parent',FigHandle, ...
      'Units','normalized', ...
      'BackgroundColor',guibuttonbackcolor, ...
      'ForegroundColor',guitextcolor,...
      'FontSize',guiFontSize, ...
      'Position',[marginleft+sampleWidth+spacing ...
         sampletxtbot+1*(2*txtHt+spacing)+smbutHt+spacing smbutWidth smbutHt], ...
      'String','Change Text Color', ...
      'UserData',EditText_H,...
      'Callback','lfosr_edit(''changetextcolor'')');
   
   
   FrameText_H = uicontrol('Parent',FigHandle, ...
      'Units','normalized', ...
      'HorizontalAlignment','left', ...
      'BackgroundColor',FrameBackColor, ...
      'ForegroundColor',FrameTextColor,...
      'FontName',FontName,...
      'FontUnits',FontUnits,...
      'FontSize',FontSize, ...
      'FontWeight',FontWeight,...
      'FontAngle',FontAngle,...
      'Position',[marginleft sampletxtbot+0*(2*txtHt+spacing) sampleWidth 2*txtHt], ...
      'String','This Is The Frame Sample Text', ...
      'Style','text');
   
   uicontrol('Parent',FigHandle, ...
      'Units','normalized', ...
      'BackgroundColor',guibuttonbackcolor, ...
      'ForegroundColor',guitextcolor,...
      'FontSize',guiFontSize, ...
      'Position',[marginleft+sampleWidth+spacing sampletxtbot+0*(2*txtHt+spacing) ...
         smbutWidth smbutHt], ...
      'UserData',FrameText_H,...
      'String','Change Background Color',...
      'Callback','lfosr_edit(''changebackcolor'')');

   uicontrol('Parent',FigHandle, ...
      'Units','normalized', ...
      'BackgroundColor',guibuttonbackcolor, ...
      'ForegroundColor',guitextcolor,...
      'FontSize',guiFontSize, ...
      'Position',[marginleft+sampleWidth+spacing ...
         sampletxtbot+0*(2*txtHt+spacing)+smbutHt+spacing smbutWidth smbutHt], ...
      'String','Change Text Color', ...
      'UserData',FrameText_H,...
      'Callback','lfosr_edit(''changetextcolor'')');
   
   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
   uicontrol('Parent',FigHandle, ...
      'Units','normalized', ...
      'BackgroundColor',guibackcolor, ...
      'ForegroundColor',guitextcolor,...
      'FontSize',guiFontSize, ...
      'Horizontalalignment','left',...
      'Position',[marginleft+sampleWidth+2*spacing+smbutWidth ...
         sampletxtbot+4*(2*txtHt+spacing)+smbutHt+spacing editWidth smbutHt], ...
      'Style','text',...
      'String','Start Figure Size');
   
   StartFigWidth_H = uicontrol('Parent',FigHandle, ...
      'Units','normalized', ...
      'BackgroundColor',guibuttonbackcolor, ...
      'ForegroundColor',guitextcolor,...
      'FontSize',guiFontSize, ...
      'Position',[marginleft+sampleWidth+2*spacing+smbutWidth ...
         sampletxtbot+4*(2*txtHt+spacing) smeditWidth smbutHt], ...
      'Style','edit',...
      'ToolTipString','Width',...
      'String',StartFigWidth);
   
   StartFigHt_H = uicontrol('Parent',FigHandle, ...
      'Units','normalized', ...
      'BackgroundColor',guibuttonbackcolor, ...
      'ForegroundColor',guitextcolor,...
      'FontSize',guiFontSize, ...
      'Position',[marginleft+sampleWidth+3*spacing+smbutWidth+smeditWidth ...
         sampletxtbot+4*(2*txtHt+spacing) smeditWidth smbutHt], ...
      'Style','edit',...
      'ToolTipString','Height',...
      'String',StartFigHt);
   
   uicontrol('Parent',FigHandle, ...
      'Units','normalized', ...
      'BackgroundColor',guibackcolor, ...
      'ForegroundColor',guitextcolor,...
      'Horizontalalignment','left',...
      'FontSize',guiFontSize, ...
      'Position',[marginleft+sampleWidth+2*spacing+smbutWidth ...
         sampletxtbot+3*(2*txtHt+spacing)+smbutHt+spacing editWidth smbutHt], ...
      'Style','text',...
      'String','Output Figure Size');
   
   OutputFigWidth_H = uicontrol('Parent',FigHandle, ...
      'Units','normalized', ...
      'BackgroundColor',guibuttonbackcolor, ...
      'ForegroundColor',guitextcolor,...
      'FontSize',guiFontSize, ...
      'Position',[marginleft+sampleWidth+2*spacing+smbutWidth ...
         sampletxtbot+3*(2*txtHt+spacing) smeditWidth smbutHt], ...
      'Style','edit',...
      'ToolTipString','Width',...
      'String',OutputFigWidth);
   
   OutputFigHt_H = uicontrol('Parent',FigHandle, ...
      'Units','normalized', ...
      'BackgroundColor',guibuttonbackcolor, ...
      'ForegroundColor',guitextcolor,...
      'FontSize',guiFontSize, ...
      'Position',[marginleft+sampleWidth+3*spacing+smbutWidth+smeditWidth ...
         sampletxtbot+3*(2*txtHt+spacing) smeditWidth smbutHt], ...
      'Style','edit',...
      'ToolTipString','Height',...
      'String',OutputFigHt);
   
   %%%%%%%%%
   
   set(FigHandle,'UserData',[FontName_H,FontUnits_H,FontSize_H,...
         FontWeight_H,FontAngle_H,StartFigText_H,OutputFigText_H,...
         ButtonText_H,EditText_H,FrameText_H,StartFigWidth_H,StartFigHt_H,...
         OutputFigWidth_H,OutputFigHt_H]);
   
   %%%%%%%%
   uicontrol('Parent',FigHandle, ...
      'Units','normalized', ...
      'BackgroundColor',guibuttonbackcolor, ...
      'ForegroundColor',guitextcolor,...
      'FontSize',guiFontSize, ...
      'Position',[.5-3*.25/2-.1 .06 .25 .07], ...
      'String','Change Font Settings', ...
      'Callback','lfosr_edit(''change'')');
   
   uicontrol('Parent',FigHandle, ...
      'Units','normalized', ...
      'BackgroundColor',guibuttonbackcolor, ...
      'ForegroundColor',guitextcolor,...
      'FontSize',guiFontSize, ...
      'Position',[.5-.25/2 .06 .25 .07], ...
      'String','Save Defaults', ...
      'Callback','lfosr_edit(''save'')');
   
   uicontrol('Parent',FigHandle, ...
      'Units','normalized', ...
      'BackgroundColor',guibuttonbackcolor, ...
      'ForegroundColor',guitextcolor,...
      'FontSize',guiFontSize, ...
      'Position',[.5+.25/2+.1 .06 .25 .07], ...
      'String','Cancel Changes', ...
      'Callback','close(gcf)');
  
  %%%%%%%%%
  
elseif strcmp(action,'save')
   HandleList      = get(gcbf,'UserData');
   
   FontName_H         = HandleList(1);
   FontUnits_H        = HandleList(2);
   FontSize_H         = HandleList(3);
   FontWeight_H       = HandleList(4);
   FontAngle_H        = HandleList(5);
   StartFigText_H     = HandleList(6);
   OutputFigText_H    = HandleList(7);
   ButtonText_H       = HandleList(8);
   EditText_H         = HandleList(9);
   FrameText_H        = HandleList(10);
   StartFigWidth_H    = HandleList(11);
   StartFigHt_H       = HandleList(12);
   OutputFigWidth_H   = HandleList(13);
   OutputFigHt_H      = HandleList(14);
   
   FontName     = get(FontName_H,'FontName');
   FontUnits    = get(FontUnits_H,'FontUnits');
   FontSize     = num2str(get(FontSize_H,'FontSize'));
   FontWeight   = get(FontWeight_H,'FontWeight');
   FontAngle    = get(FontAngle_H,'FontAngle');
   StartFigTextColor    = num2str(get(StartFigText_H,'ForegroundColor'));
   StartFigBackColor    = num2str(get(StartFigText_H,'BackgroundColor'));
   OutputFigTextColor   = num2str(get(OutputFigText_H,'ForegroundColor'));
   OutputFigBackColor   = num2str(get(OutputFigText_H,'BackgroundColor'));
   ButtonTextColor      = num2str(get(ButtonText_H,'ForegroundColor'));
   ButtonBackColor      = num2str(get(ButtonText_H,'BackgroundColor'));
   EditTextColor        = num2str(get(EditText_H,'ForegroundColor'));
   EditBackColor        = num2str(get(EditText_H,'BackgroundColor'));
   FrameTextColor       = num2str(get(FrameText_H,'ForegroundColor'));
   FrameBackColor       = num2str(get(FrameText_H,'BackgroundColor'));
   StartFigWidth        = get(StartFigWidth_H,'String');
   StartFigHt           = get(StartFigHt_H,'String');
   OutputFigWidth       = get(OutputFigWidth_H,'String');
   OutputFigHt          = get(OutputFigHt_H,'String');

   %[path,name,ext] = fileparts(which(mfilename));
   
   %path and name of file plus Text Extension
   if isunix == 1
      fid = fopen('lfosr_unixfont.txt','wt');
      
   % This is the font set up for all other systems
   else
      fid = fopen('lfosr_pcfont.txt','wt');
      
   end
   
   if fid == -1 %check for error on open
      error('Unable to open file.')
   end
   
   fprintf(fid,'%s\n',FontName);
   fprintf(fid,'%s\n',FontUnits);
   fprintf(fid,'%s\n',FontSize);
   fprintf(fid,'%s\n',FontWeight);
   fprintf(fid,'%s\n',FontAngle);
   fprintf(fid,'%s\n',StartFigTextColor);
   fprintf(fid,'%s\n',StartFigBackColor);
   fprintf(fid,'%s\n',OutputFigTextColor);
   fprintf(fid,'%s\n',OutputFigBackColor);
   fprintf(fid,'%s\n',ButtonTextColor);
   fprintf(fid,'%s\n',ButtonBackColor);
   fprintf(fid,'%s\n',EditTextColor);
   fprintf(fid,'%s\n',EditBackColor);
   fprintf(fid,'%s\n',FrameTextColor);
   fprintf(fid,'%s\n',FrameBackColor);
   fprintf(fid,'%s\n',StartFigWidth);
   fprintf(fid,'%s\n',StartFigHt);
   fprintf(fid,'%s\n',OutputFigWidth);
   fprintf(fid,'%s\n',OutputFigHt);
   fclose(fid);
   disp('Settings saved successfully')
   
   close(gcf)
   
elseif strcmp(action,'change')
   HandleList         = get(gcbf,'UserData');
   
   FontName_H         = HandleList(1);
   FontUnits_H        = HandleList(2);
   FontSize_H         = HandleList(3);
   FontWeight_H       = HandleList(4);
   FontAngle_H        = HandleList(5);
   StartFigText_H     = HandleList(6);
   OutputFigText_H    = HandleList(7);
   ButtonText_H       = HandleList(8);
   EditText_H         = HandleList(9);
   FrameText_H        = HandleList(10);
   
   FontNameSizeWeight = uisetfont(FontName_H,'Change Text Settings');
   
   if isstruct(FontNameSizeWeight)
      set(StartFigText_H,FontNameSizeWeight)
      set(OutputFigText_H,FontNameSizeWeight)
      set(ButtonText_H,FontNameSizeWeight)
      set(EditText_H,FontNameSizeWeight)
      set(FrameText_H,FontNameSizeWeight)
      
      set(  FontName_H,FontNameSizeWeight)
      set( FontUnits_H,FontNameSizeWeight)
      set(  FontSize_H,FontNameSizeWeight)
      set(FontWeight_H,FontNameSizeWeight)
      set( FontAngle_H,FontNameSizeWeight)
      
      set(  FontName_H,'String',FontNameSizeWeight.FontName)
      set( FontUnits_H,'String',FontNameSizeWeight.FontUnits)
      set(  FontSize_H,'String',FontNameSizeWeight.FontSize)
      set(FontWeight_H,'String',FontNameSizeWeight.FontWeight)
      set( FontAngle_H,'String',FontNameSizeWeight.FontAngle)
   end
   
elseif strcmp(action,'changebackcolor')
   CallBackObject          = get(gcbo,'UserData');
   CallBackObjectColor     = get(CallBackObject,'BackgroundColor');
   
   CallBackObjectBackColor = uisetcolor(CallBackObjectColor,'Change Background Color');
   
   if ~isempty(CallBackObjectBackColor)
      set(CallBackObject,'BackgroundColor',CallBackObjectBackColor)
   end
   
   
elseif strcmp(action,'changetextcolor')
   CallBackObject          = get(gcbo,'UserData');
   CallBackObjectColor     = get(CallBackObject,'ForegroundColor');
   
   CallBackObjectTextColor = uisetcolor(CallBackObjectColor,'Change Text Color');
   
   if ~isempty(CallBackObjectTextColor)
      set(CallBackObject,'ForegroundColor',CallBackObjectTextColor)
   end
   
end

return
