function []=lfosr_output(CallBack_h,FVersion,path_data,lambda_data,theta_data,thickness_data,...
    refractive_index_data,Answer_Matrix,Layer,Length,Percentage_Length,Sweep_Variable,Slider_Bar,Timedebug,User_selection,Line_suppress)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  lfosr_output.m                                                   %%
%  Date: 2/27/2001                                                  %%
%  Version: 1.0                                                     %%
%  Authors:  Matthew K. Emsley                                      %%
%            Rachel L. Kaplan                                       %%
%                                                                   %%
%  Updates:                                                         %%
%           v1.0 2/27/2001 - First Release                          %%
%                                                                   %%
%  Description:  film_output.m creates figures for plotting with    %%
%                tools for data manipulation                        %%
%                                                                   %%
%  Inputs:  FVersion == program version ID                          %%
%           path_data == string with structure path name            %%
%           lambda_data == lambda array used for adjustment         %%
%           theta_data == theta array used for adjustment           %%
%           thickness_data == thickness matrix used for adjustment  %%
%           refractive_index_data == N matrix used for adjustment   %%
%           RR == reflectance result of initial structure           %%
%           TT == transmittance result of initial structure         %%
%           PP == phase result of initial structure                 %%
%           Sweep_Variable == indentifies sweep variable            %%
%           Slider_Bar == flag to show slider bar figures           %%
%           Timedebug == flag to show routine timing                %%
%                                                                   %%
%  Outputs: []                                                      %%
%                                                                   %%
%  Supporting Files:  film_adjust.m - modifiys structure and plots  %%
%                     film_plot.m - plots RR,TT,PP data             %%
%                                                                   %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if nargin~=16 %check for proper number of input arguments
    error('Incorrect number of input arguments.')
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%% PLOTTING AND PROGRAM OUTPUT %%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
c1=clock;
if ~Line_suppress
    disp('Processing Outputs.....')
end

Who_Called=get(CallBack_h,'Tag');
switch lower(Who_Called)
case 'film'
    RR=Answer_Matrix(1:3,:);
    TT=Answer_Matrix(4:6,:);
    PP=Answer_Matrix(7:9,:);
    Figure_title='Film';
case 'detector'
    QE=Answer_Matrix;
    Figure_title='QE';
otherwise
    error('Unsupported program call.')
end

dataPos=[0 0 1 1];

[StartFigTextColor,StartFigBackColor,OutputFigTextColor,OutputFigBackColor,...
        ButtonTextColor,ButtonBackColor,EditTextColor,EditBackColor,...
        FrameTextColor,FrameBackColor,FontName,FontUnits,FontWeight,FontAngle,...
        TitleTextFontSize,HeaderTextFontSize,BodyTextFontSize,Body2TextFontSize,...
        SmallTextFontSize,ButtonFontSize,SmallButtonFontSize,...
        StartFigWidth,StartFigHt,OutputFigWidth,OutputFigHt]=lfosr_fontscolors;

if Slider_Bar
    %====================================
    % Information for all buttons
    figLeft=132;
    figBottom=78;
    figWidth=OutputFigWidth;
    figHt=OutputFigHt;
    
    bottom=0.05;    
    top=0.705;
    topbtn=0.17;
    left=0.74;
    width=0.30;
    frmBorder=0.06;
    slwidth=0.02;
    
    btnWid=0.27;
    btnHt=0.04;
    
    sldWid=0.18;   
    
    editHt=0.04;
    smeditWid=0.045;
    
    txtHt=0.03;
    txtWid=.22;
    txtLeft=.72;
    
    frmcenter=left-frmBorder+width/2;
    spacing1=0.02;   % Spacing between the button and the next command's label
    spacing2=0.01;
    spacing3=0.01;
    %====================================

    handle_fcf=figure('Name',['LFOSR ',Figure_title,'Calc v',num2str(FVersion)],...
        'NumberTitle','off',...
        'Position',[figLeft figBottom figWidth figHt],...
        'Color',OutputFigBackColor,'Visible','off','Pointer','watch');
%'WindowStyle','modal',
    if versionnumber>=5.3
        set(handle_fcf,'DoubleBuffer','on');
    end
    
    handle_fca=axes('Parent',handle_fcf,'Units','normalized',...
        'Position',[0.08 0.11 0.55 0.80]);
    
    path_data_h=uicontrol(handle_fcf,'Style','text','Position',dataPos,...
        'BackgroundColor',OutputFigBackColor,'Userdata',path_data);
    lambda_data_h=uicontrol(handle_fcf,'Style','text','Position',dataPos,...
        'BackgroundColor',OutputFigBackColor,'Userdata',lambda_data);
    theta_data_h=uicontrol(handle_fcf,'Style','text','Position',dataPos,...
        'BackgroundColor',OutputFigBackColor,'Userdata',theta_data);
    thickness_data_h=uicontrol(handle_fcf,'Style','text','Position',dataPos,...
        'BackgroundColor',OutputFigBackColor,'Userdata',thickness_data);
    thickness_data_original_h=uicontrol(handle_fcf,'Style','text','Position',dataPos,...
        'BackgroundColor',OutputFigBackColor,'Userdata',thickness_data);
    refractive_index_data_h=uicontrol(handle_fcf,'Style','text','Position',dataPos,...
        'BackgroundColor',OutputFigBackColor,'Userdata',refractive_index_data);
    refractive_index_original_h=uicontrol(handle_fcf,'Style','text','Position',dataPos,...
        'BackgroundColor',OutputFigBackColor,'Userdata',refractive_index_data);
    
    Layer_numbers_1_default=2;
    Layer_numbers_1_previous_h=uicontrol(handle_fcf,'Style','text','Position',dataPos,...
        'BackgroundColor',OutputFigBackColor,'Userdata',Layer_numbers_1_default);
    Layer_numbers_2_default=2;
    Layer_numbers_2_previous_h=uicontrol(handle_fcf,'Style','text','Position',dataPos,...
        'BackgroundColor',OutputFigBackColor,'Userdata',Layer_numbers_2_default);
    
    User_selection_h=uicontrol(handle_fcf,'Style','text','Position',dataPos,...
        'BackgroundColor',OutputFigBackColor,'Userdata',User_selection);
    %====================================
    % The CONSOLE frame
    yPos=0.08-frmBorder;
    frmPos=[left-frmBorder yPos width 3*(0.84+2*frmBorder)/12];
    uicontrol(handle_fcf, ...
        'Style','frame', ...
        'Units','normalized', ...
        'Position',frmPos, ...
        'BackgroundColor',FrameBackColor);
    totfrmPos=frmPos(4);
    
    yPos=0.08-frmBorder+totfrmPos;
    frmPos=[left-frmBorder yPos width 2*(0.84+2*frmBorder)/12];
    uicontrol(handle_fcf, ...
        'Style','frame', ...
        'Units','normalized', ...
        'Position',frmPos, ...
        'BackgroundColor',FrameBackColor);
    totfrmPos=frmPos(4)+totfrmPos;   
    
    yPos=0.08-frmBorder+totfrmPos;
    frmPos=[left-frmBorder yPos width 3.5*(0.84+2*frmBorder)/12];
    uicontrol(handle_fcf, ...
        'Style','frame', ...
        'Units','normalized', ...
        'Position',frmPos, ...
        'BackgroundColor',FrameBackColor);
    totfrmPos=frmPos(4)+totfrmPos;   
    
    yPos=0.08-frmBorder+totfrmPos;
    frmPos=[left-frmBorder yPos width 3.5*(0.84+2*frmBorder)/12];
    uicontrol(handle_fcf, ...
        'Style','frame', ...
        'Units','normalized', ...
        'Position',frmPos, ...
        'BackgroundColor',FrameBackColor);
    
    %====================================
    % The Slider Bar
    btnNumber=1;
    yPos=top-(btnNumber-1)*((txtHt+spacing3)*2+editHt+txtHt+spacing3+btnHt+editHt+txtHt+spacing2);
    Slider_1_value=1;
    
    txtPos=[txtLeft yPos+(txtHt+spacing3)*2+editHt+txtHt+spacing3+btnHt+editHt txtWid txtHt];
    uicontrol(handle_fcf, ...
        'Style','text',...
        'ForegroundColor',FrameTextColor,...
        'BackgroundColor',FrameBackColor, ...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',Body2TextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'String','Thickness Ratio', ...
        'Units','normalized', ...
        'Position',txtPos);
    
    edtPos=[frmcenter+sldWid/2 yPos+(txtHt+spacing3)*2+editHt+txtHt+spacing3+...
            (btnHt-editHt)/2 smeditWid editHt];
    Slider_1_max_h=uicontrol(handle_fcf, ...
        'Style','edit', ...
        'ForegroundColor',EditTextColor,...
        'BackgroundColor',EditBackColor, ...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',Body2TextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','right', ...
        'Units','normalized', ...
        'Position',edtPos);
    
    edtPos=[frmcenter-sldWid/2-smeditWid yPos+(txtHt+spacing3)*2+editHt+txtHt+spacing3+...
            (btnHt-editHt)/2 smeditWid editHt];
    Slider_1_min_h=uicontrol(handle_fcf, ...
        'Style','edit', ...
        'ForegroundColor',EditTextColor,...
        'BackgroundColor',EditBackColor, ...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',Body2TextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','right', ...
        'Units','normalized', ...
        'Position',edtPos);
    
    edtPos=[frmcenter-sldWid/2+slwidth yPos+(txtHt+spacing3)*2+editHt+txtHt+spacing3+btnHt...
            sldWid-2*slwidth editHt];
    Slider_1_value_h=uicontrol(handle_fcf, ...
        'Style','edit', ...
        'ForegroundColor',EditTextColor,...
        'BackgroundColor',EditBackColor, ...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',Body2TextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','right', ...
        'Units','normalized', ...
        'Position',edtPos, ...
        'String',Slider_1_value);
    
    btnPos=[frmcenter-sldWid/2 yPos+(txtHt+spacing3)*2+editHt+txtHt+spacing3 sldWid btnHt];
    Slider_1_h=uicontrol(handle_fcf, ...
        'Style','slider', ...
        'Units','normalized', ...
        'Position',btnPos, ...
        'Min',0.5, ...
        'Max',1.5, ...
        'Sliderstep',[0.001 0.01], ...
        'Value',Slider_1_value);
    
    %====================================
    % The Layer Input
    txtPos=[txtLeft yPos+(txtHt+spacing3)*2+editHt txtWid txtHt];
    uicontrol( ...
        'Style','text',...
        'ForegroundColor',FrameTextColor,...
        'BackgroundColor',FrameBackColor, ...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',Body2TextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'String','Layers', ...
        'Units','normalized', ...
        'Position',txtPos);
    
    edtPos=[frmcenter-sldWid/2+slwidth yPos+(txtHt+spacing3)*2 sldWid-2*slwidth editHt];
    Layer_numbers_1_h=uicontrol(handle_fcf, ...
        'Style','edit', ...
        'ForegroundColor',EditTextColor,...
        'BackgroundColor',EditBackColor, ...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',Body2TextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','right', ...
        'Units','normalized', ...
        'Position',edtPos, ...
        'String',Layer_numbers_1_default);
    
    edtPos=[txtLeft yPos+txtHt+spacing3 txtWid txtHt];
    Sticky_1_h=uicontrol(handle_fcf, ...
        'Style','checkbox', ...
        'ForegroundColor',FrameTextColor,...
        'BackgroundColor',FrameBackColor, ...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',Body2TextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'Units','normalized', ...
        'Position',edtPos, ...
        'String','Sticky Changes');
    
    edtPos=[txtLeft yPos txtWid txtHt];
    Display_1_h=uicontrol(handle_fcf, ...
        'Style','checkbox', ...
        'ForegroundColor',FrameTextColor,...
        'BackgroundColor',FrameBackColor, ...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',Body2TextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'Units','normalized', ...
        'Position',edtPos, ...
        'String','Display Thickness');
    %====================================
    
    %====================================
    % The Slider Bar 2
    btnNumber=2;
    yPos=top-(btnNumber-1)*((txtHt+spacing3)*2+editHt+txtHt+spacing3+btnHt+editHt+txtHt+spacing2);
    Slider_2_value=1;
    
    txtPos=[txtLeft yPos+(txtHt+spacing3)*2+editHt+txtHt+spacing3+btnHt+editHt txtWid txtHt];
    uicontrol(handle_fcf, ...
        'Style','text',...
        'ForegroundColor',FrameTextColor,...
        'BackgroundColor',FrameBackColor, ...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',Body2TextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'String','Refractive Index Ratio', ...
        'Units','normalized', ...
        'Position',txtPos);
    
    edtPos=[frmcenter+sldWid/2 yPos+(txtHt+spacing3)*2+editHt+txtHt+spacing3+...
            (btnHt-editHt)/2 smeditWid editHt];
    Slider_2_max_h=uicontrol(handle_fcf, ...
        'Style','edit', ...
        'ForegroundColor',EditTextColor,...
        'BackgroundColor',EditBackColor, ...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',Body2TextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','right', ...
        'Units','normalized', ...
        'Position',edtPos);
    
    edtPos=[frmcenter-sldWid/2-smeditWid yPos+(txtHt+spacing3)*2+editHt+txtHt+spacing3+...
            (btnHt-editHt)/2 smeditWid editHt];
    Slider_2_min_h=uicontrol(handle_fcf, ...
        'Style','edit', ...
        'ForegroundColor',EditTextColor,...
        'BackgroundColor',EditBackColor, ...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',Body2TextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','right', ...
        'Units','normalized', ...
        'Position',edtPos);
    
    edtPos=[frmcenter-sldWid/2+slwidth yPos+(txtHt+spacing3)*2+editHt+txtHt+spacing3+btnHt...
            sldWid-2*slwidth editHt];
    Slider_2_value_h=uicontrol(handle_fcf, ...
        'Style','edit', ...
        'ForegroundColor',EditTextColor,...
        'BackgroundColor',EditBackColor, ...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',Body2TextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','right', ...
        'Units','normalized', ...
        'Position',edtPos, ...
        'String',Slider_2_value);
    
    btnPos=[frmcenter-sldWid/2 yPos+(txtHt+spacing3)*2+editHt+txtHt+spacing3 sldWid btnHt];
    Slider_2_h=uicontrol(handle_fcf, ...
        'Style','slider', ...
        'Units','normalized', ...
        'Position',btnPos, ...
        'Min',0.5, ...
        'Max',1.5, ...
        'Sliderstep',[0.001 0.01], ...
        'Value',Slider_2_value);
    
    %====================================
    % The Layer Input
    txtPos=[txtLeft yPos+(txtHt+spacing3)*2+editHt txtWid/2 txtHt];
    uicontrol( ...
        'Style','text',...
        'ForegroundColor',FrameTextColor,...
        'BackgroundColor',FrameBackColor, ...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',Body2TextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'String','Layers', ...
        'Units','normalized', ...
        'Position',txtPos);
    
    txtPos=[txtLeft+txtWid/2 yPos+(txtHt+spacing3)*2+editHt txtWid/4 txtHt];
    n_change_h=uicontrol( ...
        'Style','checkbox',...
        'ForegroundColor',FrameTextColor,...
        'BackgroundColor',FrameBackColor, ...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',Body2TextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'String','n', ...
        'Units','normalized', ...
        'Value',1, ...
        'Position',txtPos);
    
    txtPos=[txtLeft+3*txtWid/4 yPos+(txtHt+spacing3)*2+editHt txtWid/4 txtHt];
    k_change_h=uicontrol( ...
        'Style','checkbox',...
        'ForegroundColor',FrameTextColor,...
        'BackgroundColor',FrameBackColor, ...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',Body2TextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'String','k', ...
        'Units','normalized', ...
        'Value',1, ...
        'Position',txtPos);
    
    edtPos=[frmcenter-sldWid/2+slwidth yPos+(txtHt+spacing3)*2 sldWid-2*slwidth editHt];
    Layer_numbers_2_h=uicontrol(handle_fcf, ...
        'Style','edit', ...
        'ForegroundColor',EditTextColor,...
        'BackgroundColor',EditBackColor, ...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',Body2TextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','right', ...
        'Units','normalized', ...
        'Position',edtPos, ...
        'String',Layer_numbers_2_default);
    
    edtPos=[txtLeft yPos+txtHt+spacing3 txtWid txtHt];
    Sticky_2_h=uicontrol(handle_fcf, ...
        'Style','checkbox', ...
        'ForegroundColor',FrameTextColor,...
        'BackgroundColor',FrameBackColor, ...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',Body2TextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'Units','normalized', ...
        'Position',edtPos, ...
        'String','Sticky Changes');
    
    edtPos=[txtLeft yPos txtWid txtHt];
    Display_2_h=uicontrol(handle_fcf, ...
        'Style','checkbox', ...
        'ForegroundColor',FrameTextColor,...
        'BackgroundColor',FrameBackColor, ...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',Body2TextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'Units','normalized', ...
        'Position',edtPos, ...
        'Visible','off',...
        'String','Display Refractive Index');
    
    %====================================
    % The Slider Bar 3
    %   btnNumber=3;
    yPos=top-yPos;
    
    txtPos=[txtLeft yPos+btnHt+editHt txtWid txtHt];
    Slider_3_text_h=uicontrol(handle_fcf, ...
        'Style','text',...
        'ForegroundColor',FrameTextColor,...
        'BackgroundColor',FrameBackColor, ...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',Body2TextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','left', ...
        'Units','normalized', ...
        'Position',txtPos);
    
    edtPos=[frmcenter+sldWid/2 yPos+(btnHt-editHt)/2 smeditWid editHt];
    Slider_3_max_h=uicontrol(handle_fcf, ...
        'Style','edit', ...
        'ForegroundColor',EditTextColor,...
        'BackgroundColor',EditBackColor, ...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',Body2TextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','right', ...
        'Units','normalized', ...
        'Position',edtPos);
    
    edtPos=[frmcenter-sldWid/2-smeditWid yPos+(btnHt-editHt)/2 smeditWid editHt];
    Slider_3_min_h=uicontrol(handle_fcf, ...
        'Style','edit', ...
        'ForegroundColor',EditTextColor,...
        'BackgroundColor',EditBackColor, ...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',Body2TextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','right', ...
        'Units','normalized', ...
        'Position',edtPos);
    
    edtPos=[frmcenter-sldWid/2+slwidth yPos+btnHt sldWid-2*slwidth editHt];
    Slider_3_value_h=uicontrol(handle_fcf, ...
        'Style','edit', ...
        'ForegroundColor',EditTextColor,...
        'BackgroundColor',EditBackColor, ...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',Body2TextFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'HorizontalAlignment','right', ...
        'Units','normalized', ...
        'Position',edtPos);
    
    btnPos=[frmcenter-sldWid/2 yPos sldWid btnHt];
    Slider_3_h=uicontrol(handle_fcf, ...
        'Style','slider', ...
        'Units','normalized', ...
        'Position',btnPos, ...
        'Sliderstep',[0.001 0.01]);
    
    %====================================
    % Reset Default Thickness Creation
    btnNumber=1;
    yPos=topbtn-(btnNumber-1)*(btnHt+spacing1);
    
    edtPos=[frmcenter-btnWid/2 yPos .499*btnWid 1.1*btnHt];
    Reset_h=uicontrol(handle_fcf, ...
        'Style','pushbutton', ...
        'Units','normalized', ...
        'ForegroundColor',ButtonTextColor,...
        'BackgroundColor',ButtonBackColor, ...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',SmallButtonFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'Position',edtPos, ...
        'String','Reset Thickness');
    
    % Reset Default Index Creation
    btnNumber=1;
    yPos=topbtn-(btnNumber-1)*(btnHt+spacing1);
    
    edtPos=[frmcenter-btnWid/2+11*btnWid/21 yPos .499*btnWid 1.1*btnHt];
    Reset_index_h=uicontrol(handle_fcf, ...
        'Style','pushbutton', ...
        'Units','normalized', ...
        'ForegroundColor',ButtonTextColor,...
        'BackgroundColor',ButtonBackColor, ...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',SmallButtonFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'Position',edtPos, ...
        'String','Reset Ref. Index');
    
    %====================================
    % Structure File Creation
    btnNumber=2;
    yPos=topbtn-(btnNumber-1)*(btnHt+spacing1);
    
    edtPos=[frmcenter-btnWid/2 yPos .499*btnWid 1.1*btnHt];
    uicontrol(handle_fcf, ...
        'Style','pushbutton', ...
        'Units','normalized', ...
        'ForegroundColor',ButtonTextColor,...
        'BackgroundColor',ButtonBackColor, ...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',SmallButtonFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'Position',edtPos, ...
        'Userdata',[path_data_h thickness_data_h Layer_numbers_1_h Slider_1_h],...
        'Callback','structure_modify(get(gcbo,''Userdata''));',...
        'String','New Struct. File');
    
    % Index File Creation
    btnNumber=2;
    yPos=topbtn-(btnNumber-1)*(btnHt+spacing1);
    
    edtPos=[frmcenter-btnWid/2+11*btnWid/21 yPos .499*btnWid 1.1*btnHt];
    uicontrol(handle_fcf, ...
        'Style','pushbutton', ...
        'Units','normalized', ...
        'ForegroundColor',ButtonTextColor,...
        'BackgroundColor',ButtonBackColor, ...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',SmallButtonFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'Position',edtPos, ...
        'Userdata',[path_data_h refractive_index_data_h Layer_numbers_2_h Slider_2_h n_change_h k_change_h],...
        'Callback','index_file_modify(get(gcbo,''Userdata''));',...
        'Visible','off',...
        'String','New Ref Idx File');
    
    %====================================
    % Close figure
    btnNumber=3;
    yPos=topbtn-(btnNumber-1)*(btnHt+spacing1);
    
    edtPos=[frmcenter-btnWid/2 yPos btnWid 1.1*btnHt];
    uicontrol(handle_fcf, ...
        'Style','pushbutton', ...
        'Units','normalized', ...
        'ForegroundColor',ButtonTextColor,...
        'BackgroundColor',ButtonBackColor, ...
        'FontName',FontName,...
        'FontUnits',FontUnits,...
        'FontSize',SmallButtonFontSize, ...
        'FontWeight',FontWeight,...
        'FontAngle',FontAngle,...
        'Position',edtPos, ...
        'Callback','close(gcf)',...
        'String','Close Figure');
    
    %====================================
    
    if versionnumber>=5.3
        set(Layer_numbers_1_h,'TooltipString','use '':'' or '','' for multiple layers')
        set(Sticky_1_h,'TooltipString','Thickness changes saved when layer is changed')
        set(Display_1_h,'TooltipString','Thickness printed in command window')
    end
    
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%   
    switch Sweep_Variable
    case 100
        Angle=theta_data;
        set(Slider_3_text_h,'String','Incident Angle')
        set(Slider_3_h,'Min',0,'Max',90,'Value',Angle)
        set(Slider_3_value_h,'String',Angle)
    case 010
        Wavelength=lambda_data;
        
        if(Wavelength-50<=0)
            Sl2_min=Wavelength;
        else
            Sl2_min=Wavelength-50;
        end
        
        set(Slider_3_text_h,'String','Incident Wavelength')
        set(Slider_3_h,'Min',Sl2_min,'Max',Wavelength+50,'Value',Wavelength)
        set(Slider_3_value_h,'String',Wavelength)
    case 001
        Angle=theta_data;
        set(Slider_3_text_h,'String','Incident Angle')
        set(Slider_3_h,'Min',0,'Max',90,'Value',Angle)
        set(Slider_3_value_h,'String',Angle)
    otherwise
        error('Unsupported sweep variable.')
    end
    
    set(Slider_1_min_h,'String',num2str(get(Slider_1_h,'Min')))
    set(Slider_1_max_h,'String',num2str(get(Slider_1_h,'Max')))
    set(Slider_2_min_h,'String',num2str(get(Slider_2_h,'Min')))
    set(Slider_2_max_h,'String',num2str(get(Slider_2_h,'Max')))
    set(Slider_3_min_h,'String',num2str(get(Slider_3_h,'Min')))
    set(Slider_3_max_h,'String',num2str(get(Slider_3_h,'Max')))
    
    %                   1              2              3                4
    %     5                 6              7              8                9
    %     10                11             12             13               14
    %     15         16          17         18          19            20           21
    %     22         23         24                      25             26    
    %     27                         28
    %     29                        30
    %     31      32            33         34    35
    SliderCallbackData={Slider_1_min_h,Slider_1_max_h,Slider_1_value_h,Slider_1_h,...
            Layer_numbers_1_h,Slider_2_min_h,Slider_2_max_h,Slider_2_value_h,Slider_2_h,...
            Layer_numbers_2_h,Slider_3_min_h,Slider_3_max_h,Slider_3_value_h,Slider_3_h,...
            Sticky_1_h,Display_1_h,Sticky_2_h,Display_2_h,lambda_data_h,theta_data_h,thickness_data_h,...
            n_change_h,k_change_h,refractive_index_data_h,Sweep_Variable,FVersion...
            Layer_numbers_1_previous_h,Layer_numbers_2_previous_h,...
            thickness_data_original_h,refractive_index_original_h,...
            Reset_h,Reset_index_h,CallBack_h,Layer,Length,User_selection_h};
    
    SliderCallbackString='lfosr_adjust(gcbo,gca,get(gcbo,''UserData''));';
    
    SliderCallbackString_invalidcheck=strcat(...
        'if isempty(str2num(get(gcbo,''String''))),error(''Invalid entry''),end,',...
        SliderCallbackString);
    
    set(Slider_1_min_h,'Userdata',SliderCallbackData,'Callback',...
        SliderCallbackString_invalidcheck);
    set(Slider_2_min_h,'Userdata',SliderCallbackData,'Callback',...
        SliderCallbackString_invalidcheck);
    set(Slider_3_min_h,'Userdata',SliderCallbackData,'Callback',...
        SliderCallbackString_invalidcheck);
    
    set(Slider_1_max_h,'Userdata',SliderCallbackData,'Callback',...
        SliderCallbackString_invalidcheck);
    set(Slider_2_max_h,'Userdata',SliderCallbackData,'Callback',...
        SliderCallbackString_invalidcheck);
    set(Slider_3_max_h,'Userdata',SliderCallbackData,'Callback',...
        SliderCallbackString_invalidcheck);
    
    set(Slider_1_value_h,'Userdata',SliderCallbackData,...
        'Callback',SliderCallbackString_invalidcheck);
    set(Slider_2_value_h,'Userdata',SliderCallbackData,...
        'Callback',SliderCallbackString_invalidcheck);
    set(Slider_3_value_h,'Userdata',SliderCallbackData,...
        'Callback',SliderCallbackString_invalidcheck);
    
    set(Slider_1_h,'Userdata',SliderCallbackData,'Callback',SliderCallbackString);
    set(Slider_2_h,'Userdata',SliderCallbackData,'Callback',SliderCallbackString);
    set(Slider_3_h,'Userdata',SliderCallbackData,'Callback',SliderCallbackString);
    
    set(Layer_numbers_1_h,'Userdata',SliderCallbackData,'Callback',...
        SliderCallbackString_invalidcheck);
    set(Layer_numbers_2_h,'Userdata',SliderCallbackData,'Callback',...
        SliderCallbackString_invalidcheck);
    set(Reset_h,'Userdata',SliderCallbackData,'Callback',SliderCallbackString);
    set(Reset_index_h,'Userdata',SliderCallbackData,'Callback',SliderCallbackString);
    
else
    handle_fcf=figure('Color',OutputFigBackColor, ...
        'Name',['LFOSR ',Figure_title,'Calc v',num2str(FVersion)],'NumberTitle','off',...
        'Visible','off','Pointer','watch');
    %'WindowStyle','modal',
    handle_fca=axes('Parent',handle_fcf);
end


%%%%%% Output %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
switch lower(Who_Called)
case 'film' %Film Called
    Variable_h  =uicontrol(handle_fcf,'Style','text','Position',dataPos,...
        'BackgroundColor',OutputFigBackColor,'Userdata',RR(1,:));
    R_TM_h      =uicontrol(handle_fcf,'Style','text','Position',dataPos,...
        'BackgroundColor',OutputFigBackColor,'Userdata',RR(2,:));
    R_TE_h      =uicontrol(handle_fcf,'Style','text','Position',dataPos,...
        'BackgroundColor',OutputFigBackColor,'Userdata',RR(3,:));
    T_TM_h      =uicontrol(handle_fcf,'Style','text','Position',dataPos,...
        'BackgroundColor',OutputFigBackColor,'Userdata',TT(2,:));
    T_TE_h      =uicontrol(handle_fcf,'Style','text','Position',dataPos,...
        'BackgroundColor',OutputFigBackColor,'Userdata',TT(3,:));
    P_TM_h      =uicontrol(handle_fcf,'Style','text','Position',dataPos,...
        'BackgroundColor',OutputFigBackColor,'Userdata',PP(2,:));
    P_TE_h      =uicontrol(handle_fcf,'Style','text','Position',dataPos,...
        'BackgroundColor',OutputFigBackColor,'Userdata',PP(3,:));
    
    switch Sweep_Variable
    case 100 %Lambda sweep
        Angle=theta_data;
        Wavelength=NaN;
        Layer=1;
        %         1        2              3     4          5     6
        Data_R_h={FVersion,Sweep_Variable,Angle,Wavelength,Layer,Percentage_Length,thickness_data(1,Layer),...
                handle_fca,Variable_h,R_TM_h,R_TE_h};
        %     7          8          9      10
        
        %         1        2              3     4          5     6
        Data_T_h={FVersion,Sweep_Variable,Angle,Wavelength,Layer,Percentage_Length,thickness_data(1,Layer),...
                handle_fca,Variable_h,T_TM_h,T_TE_h};
        %     7          8          9      10
        
        %         1        2              3     4          5     6
        Data_P_h={FVersion,Sweep_Variable,Angle,Wavelength,Layer,Percentage_Length,thickness_data(1,Layer),...
                handle_fca,Variable_h,P_TM_h,P_TE_h};
        %     7          8          9      10
        
        handle_R = uimenu(handle_fcf,'Label','Reflectance');
        uimenu(handle_R,'Label','Replot versus Wavelength','UserData',Data_R_h,...
            'Callback','lfosr_plotinfo(get(gcbo,''Userdata''),''wavelength'',''reflectance'');');
        
        uimenu(handle_R,'Label','Replot versus Energy','UserData',Data_R_h,...
            'Callback','lfosr_plotinfo(get(gcbo,''Userdata''),''energy'',''reflectance'');');
        
        handle_T = uimenu(handle_fcf,'Label','Transmittance');
        uimenu(handle_T,'Label','Replot versus Wavelength','UserData',Data_T_h,...
            'Callback','lfosr_plotinfo(get(gcbo,''Userdata''),''wavelength'',''transmittance'');');
        
        uimenu(handle_T,'Label','Replot versus Energy','UserData',Data_T_h,...
            'Callback','lfosr_plotinfo(get(gcbo,''Userdata''),''energy'',''transmittance'');');
        
        handle_P=uimenu(handle_fcf,'Label','Phase');
        uimenu(handle_P,'Label','Replot versus Wavelength','UserData',Data_P_h,...
            'Callback','lfosr_plotinfo(get(gcbo,''Userdata''),''wavelength'',''phase'');');
        
        uimenu(handle_P,'Label','Replot versus Energy','UserData',Data_P_h,...
            'Callback','lfosr_plotinfo(get(gcbo,''Userdata''),''energy'',''phase'');');
        
        Variable_Type='''Lambda''';
        
    case 010 %theta sweep
        Angle=NaN;
        Wavelength=lambda_data;
        
        %         1        2              3     4          5     6
        Data_R_h={FVersion,Sweep_Variable,Angle,Wavelength,Layer,Percentage_Length,thickness_data(1,Layer),...
                handle_fca,Variable_h,R_TM_h,R_TE_h};
        %     7          8          9      10
        
        %         1        2              3     4          5     6
        Data_T_h={FVersion,Sweep_Variable,Angle,Wavelength,Layer,Percentage_Length,thickness_data(1,Layer),...
                handle_fca,Variable_h,T_TM_h,T_TE_h};
        %     7          8          9      10
        
        %         1        2              3     4          5     6
        Data_P_h={FVersion,Sweep_Variable,Angle,Wavelength,Layer,Percentage_Length,thickness_data(1,Layer),...
                handle_fca,Variable_h,P_TM_h,P_TE_h};
        %     7          8          9      10
        
        uimenu(handle_fcf,'Label','Reflectance','UserData',Data_R_h,...
            'Callback','lfosr_plotinfo(get(gcbo,''Userdata''),''wavelength'',''reflectance'');');
        
        uimenu(handle_fcf,'Label','Transmittance','UserData',Data_T_h,...
            'Callback','lfosr_plotinfo(get(gcbo,''Userdata''),''wavelength'',''transmittance'');');
        
        uimenu(handle_fcf,'Label','Phase','UserData',Data_P_h,...
            'Callback','lfosr_plotinfo(get(gcbo,''Userdata''),''wavelength'',''phase'');');
        
        Variable_Type='''Theta''';
        
    case 001 %thickness sweep
        Angle=theta_data;
        Wavelength=lambda_data;
        
        %         1        2              3     4          5     6
        Data_R_h={FVersion,Sweep_Variable,Angle,Wavelength,Length,Percentage_Length,thickness_data(1,Length),...
                handle_fca,Variable_h,R_TM_h,R_TE_h};
        %     7          8          9      10
        
        %         1        2              3     4          5     6
        Data_T_h={FVersion,Sweep_Variable,Angle,Wavelength,Length,Percentage_Length,thickness_data(1,Length),...
                handle_fca,Variable_h,T_TM_h,T_TE_h};
        %     7          8          9      10
        
        %         1        2              3     4          5     6
        Data_P_h={FVersion,Sweep_Variable,Angle,Wavelength,Length,Percentage_Length,thickness_data(1,Length),...
                handle_fca,Variable_h,P_TM_h,P_TE_h};
        %     7          8          9      10
        
        uimenu(handle_fcf,'Label','Reflectance','UserData',Data_R_h,...
            'Callback','lfosr_plotinfo(get(gcbo,''Userdata''),''wavelength'',''reflectance'');');
        
        uimenu(handle_fcf,'Label','Transmittance','UserData',Data_T_h,...
            'Callback','lfosr_plotinfo(get(gcbo,''Userdata''),''wavelength'',''transmittance'');');
        
        uimenu(handle_fcf,'Label','Phase','UserData',Data_P_h,...
            'Callback','lfosr_plotinfo(get(gcbo,''Userdata''),''wavelength'',''phase'');');
        
        Variable_Type='''A_Thickness''';
        
    otherwise
        error('Unsupported sweep variable.')
    end
    
    handle_m = uimenu(handle_fcf,'Label','Workspace');
    uimenu(handle_m,'Label','Save Reflectance Data','UserData',RR,'Callback',...
        strcat('save_file(get(gcbo,''Userdata''),''_ref'',',Variable_Type,',''TM'',''TE'')'));
    uimenu(handle_m,'Label','Save Transmittance Data','UserData',TT,'Callback',...
        strcat('save_file(get(gcbo,''Userdata''),''_trans'',',Variable_Type,',''TM'',''TE'')'));
    uimenu(handle_m,'Label','Save Phase Data','UserData',PP,'Callback',...
        strcat('save_file(get(gcbo,''Userdata''),''_phase'',',Variable_Type,',''TM'',''TE'')'));
    uimenu(handle_m,'Label','Load Comma Separated Data','UserData',handle_fca,'Callback',...
        'read_file(get(gcbo,''Userdata''),''comma'')');
    uimenu(handle_m,'Label','Load Space Separated Data','UserData',handle_fca,'Callback',...
        'read_file(get(gcbo,''Userdata''),''space'')');
    uimenu(handle_m,'Label','Load Tab Separated Data','UserData',handle_fca,'Callback',...
        'read_file(get(gcbo,''Userdata''),''tab'')');
    
    if versionnumber>=5.3
        uimenu(handle_m,'Label','Save Figure to Postscript',...
            'UserData',handle_fcf,'Callback','save_figure(get(gcbo,''Userdata''),''eps'')');
        uimenu(handle_m,'Label','Save Figure to JPEG',...
            'UserData',handle_fcf,'Callback','save_figure(get(gcbo,''Userdata''),''jpeg'')');
    end
    
    lfosr_plotinfo(Data_R_h,'wavelength','reflectance')
    
case 'detector' %Detector Called
    Variable_h   =uicontrol(handle_fcf,'Style','text','Position',dataPos,...
        'BackgroundColor',OutputFigBackColor,'Userdata',QE(1,:));
    QE_TM_h      =uicontrol(handle_fcf,'Style','text','Position',dataPos,...
        'BackgroundColor',OutputFigBackColor,'Userdata',QE(2,:));
    QE_TE_h      =uicontrol(handle_fcf,'Style','text','Position',dataPos,...
        'BackgroundColor',OutputFigBackColor,'Userdata',QE(3,:));
    
    h          =6.62617e-34;        %Planck constant [J.s]
    q          =1.60218e-19;        %Elementary charge [C]
    c          =2.998e8*1e9;        %Speed of Light in Vacuum [nm/s]
    
    switch Sweep_Variable
    case 100 %Lambda sweep
        Angle=theta_data;
        Wavelength=NaN;
        
        RV(1,:)=QE(1,:);
        RV(2,:)=QE(2,:).*(q/h/c).*QE(1,:);
        RV(3,:)=QE(3,:).*(q/h/c).*QE(1,:);
        
        %          1        2              3     4          5     6
        Data_QE_h={FVersion,Sweep_Variable,Angle,Wavelength,Length,Percentage_Length,thickness_data(1,Layer),...
                handle_fca,Variable_h,QE_TM_h,QE_TE_h};
        %     7          8          9      10
        
        handle_QE=uimenu(handle_fcf,'Label','Quantum Efficiency');
        uimenu(handle_QE,'Label','Replot versus Wavelength','UserData',Data_QE_h,...
            'Callback','lfosr_plotinfo(get(gcbo,''Userdata''),''wavelength'',''efficiency'');');
        
        uimenu(handle_QE,'Label','Replot versus Energy','UserData',Data_QE_h,...
            'Callback','lfosr_plotinfo(get(gcbo,''Userdata''),''energy'',''efficiency'');');
        
        handle_RS=uimenu(handle_fcf,'Label','Responsivity');
        uimenu(handle_RS,'Label','Replot versus Wavelength','UserData',Data_QE_h,...
            'Callback','lfosr_plotinfo(get(gcbo,''Userdata''),''wavelength'',''responsivity'');');
        
        uimenu(handle_RS,'Label','Replot versus Energy','UserData',Data_QE_h,...
            'Callback','lfosr_plotinfo(get(gcbo,''Userdata''),''energy'',''responsivity'');');
        
        Variable_Type='''Lambda''';
        
    case 010 %theta sweep
        Angle=NaN;
        Wavelength=lambda_data;
        
        RV(1,:)=QE(1,:);
        RV(2,:)=QE(2,:).*(q/h/c).*Wavelength;
        RV(3,:)=QE(3,:).*(q/h/c).*Wavelength;
        
        %          1        2              3     4          5     6
        Data_QE_h={FVersion,Sweep_Variable,Angle,Wavelength,Length,Percentage_Length,thickness_data(1,Layer),...
                handle_fca,Variable_h,QE_TM_h,QE_TE_h};
        %     7          8          9       10
        
        uimenu(handle_fcf,'Label','Quantum Efficiency','UserData',Data_QE_h,...
            'Callback','lfosr_plotinfo(get(gcbo,''Userdata''),''wavelength'',''efficiency'');');
        
        uimenu(handle_fcf,'Label','Responsivity','UserData',Data_QE_h,...
            'Callback','lfosr_plotinfo(get(gcbo,''Userdata''),''wavelength'',''responsivity'');');
        
        Variable_Type='''Theta''';
        
    case 001 %thickness sweep
        Angle=theta_data;
        Wavelength=lambda_data;
        
        RV(1,:)=QE(1,:);
        RV(2,:)=QE(2,:).*(q/h/c).*Wavelength;
        RV(3,:)=QE(3,:).*(q/h/c).*Wavelength;
        
        %          1        2              3     4          5     6
        Data_QE_h={FVersion,Sweep_Variable,Angle,Wavelength,Length,Percentage_Length,thickness_data(1,Length),...
                handle_fca,Variable_h,QE_TM_h,QE_TE_h,};
        %     7          8          9       10

        uimenu(handle_fcf,'Label','Quantum Efficiency','UserData',Data_QE_h,...
            'Callback','lfosr_plotinfo(get(gcbo,''Userdata''),''wavelength'',''efficiency'');');
        
        uimenu(handle_fcf,'Label','Responsivity','UserData',Data_QE_h,...
            'Callback','lfosr_plotinfo(get(gcbo,''Userdata''),''wavelength'',''responsivity'');');
        
        Variable_Type='''A_Thickness''';
        
    otherwise
        error('Unsupported sweep variable.')
        
    end
    
    
    handle_m=uimenu(handle_fcf,'Label','Workspace');
    uimenu(handle_m,'Label','Save Quantum Efficiency Data','UserData',QE,'Callback',...
        strcat('save_file(get(gcbo,''Userdata''),''_qe'',',Variable_Type,',''TM'',''TE'')'));
    uimenu(handle_m,'Label','Save Responsivity Data','UserData',RV,'Callback',...
        strcat('save_file(get(gcbo,''Userdata''),''_resp'',',Variable_Type,',''TM'',''TE'')'));
    uimenu(handle_m,'Label','Load Comma Separated Data','UserData',handle_fca,'Callback',...
        'read_file(get(gcbo,''Userdata''),''comma'')');
    uimenu(handle_m,'Label','Load Space Separated Data','UserData',handle_fca,'Callback',...
        'read_file(get(gcbo,''Userdata''),''space'')');
    uimenu(handle_m,'Label','Load Tab Separated Data','UserData',handle_fca,'Callback',...
        'read_file(get(gcbo,''Userdata''),''tab'')');
    
    if versionnumber>=5.3
        uimenu(handle_m,'Label','Save Figure to Postscript',...
            'UserData',handle_fcf,'Callback','save_figure(get(gcbo,''Userdata''),''eps'')');
        uimenu(handle_m,'Label','Save Figure to JPEG',...
            'UserData',handle_fcf,'Callback','save_figure(get(gcbo,''Userdata''),''jpeg'')');
    end

    if strcmpi(User_selection,'solar')
        lfosr_plotinfo(Data_QE_h,'wavelength','solar')
    else
        lfosr_plotinfo(Data_QE_h,'wavelength','efficiency')
    end
    
otherwise
    error('Unsupported program call.')
    
end

set(handle_fcf,'Visible','on','Pointer','arrow')
%,'WindowStyle','normal'
drawnow;

c2=clock;
if ~Line_suppress
    disp('   < Output Processing Complete >')
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%% END PLOTTING AND PROGRAM OUTPUT %%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%TIMING DEBUG OUTPUT %%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if Timedebug==1
    disp(' ')
    disp(' lfosr_output.m Timing Parameters         ')
    disp('------------------------------------------')
    disp(['            Output files = ',num2str(etime(c2,c1),'%-6.3f'),' seconds'])
    disp(' ')
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%% END TIMING DEBUG OUTPUT %%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
return
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%% END PROGRAM  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
