function lfosr_plot(Variable,TM,TE,handle_fca,TitleString,XlabelString,YlabelString,...
   Start,Stop,X_tick,Y_min,Y_max,Y_tick)

[StartFigTextColor,StartFigBackColor,OutputFigTextColor,OutputFigBackColor,...
      ButtonTextColor,ButtonBackColor,EditTextColor,EditBackColor,...
      FrameTextColor,FrameBackColor,FontName,FontUnits,FontWeight,FontAngle,...
      TitleTextFontSize,HeaderTextFontSize,BodyTextFontSize,Body2TextFontSize,...
      SmallTextFontSize,ButtonFontSize,SmallButtonFontSize,...
      StartFigWidth,StartFigHt,OutputFigWidth,OutputFigHt]=lfosr_fontscolors;

if versionnumber<5.3
   cla      
end

handle_sim = plot(Variable,TM,Variable,TE,'LineWidth',3,'Parent',handle_fca);
handle_leg = legend(handle_fca,'TM','TE',0);
set(handle_leg,'LineWidth',2)
set(handle_sim(1),'Color',[0 0 1],'LineStyle','-.')
set(handle_sim(2),'Color',[0 .5 0],'LineStyle',':')
title(handle_fca,...
   'FontName',FontName,...
   'FontUnits',FontUnits,...
   'FontSize',BodyTextFontSize, ...
   'FontWeight',FontWeight,...
   'FontAngle',FontAngle,...
   'Color',OutputFigTextColor,...
   'String',TitleString)
xlabel(handle_fca,...
   'FontName',FontName,...
   'FontUnits',FontUnits,...
   'FontSize',BodyTextFontSize, ...
   'FontWeight',FontWeight,...
   'FontAngle',FontAngle,...
   'Color',OutputFigTextColor,...
   'String',XlabelString)
ylabel(handle_fca,...
   'FontName',FontName,...
   'FontUnits',FontUnits,...
   'FontSize',BodyTextFontSize, ...
   'FontWeight',FontWeight,...
   'FontAngle',FontAngle,...
   'Color',OutputFigTextColor,...
   'String',YlabelString)
set(handle_fca,...
   'FontName',FontName,...
   'FontUnits',FontUnits,...
   'FontSize',BodyTextFontSize, ...
   'FontWeight',FontWeight,...
   'FontAngle',FontAngle,...
   'XColor',OutputFigTextColor,...
   'YColor',OutputFigTextColor)

axis([Start Stop  Y_min Y_max])

if ~isempty(Y_tick)
   set(handle_fca,'YTick',Y_tick)
end

if ~isempty(X_tick)
   set(handle_fca,'XTick',X_tick)
end

set(handle_fca,'LineWidth',2.0)

%
% Set user data to line handles for later use
%  TM = 1, TE = 2
%
set(handle_fca,'Userdata',handle_sim)

%
% Turn on grid
%
set(handle_fca,'XGrid','on','YGrid','on','gridlinestyle','-')